version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: rover_db
    restart: always
    environment:
      - POSTGRES_USER=mert
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=roverdb
    ports:
      - "54320:5432"  # DBeaver uses 54320, App uses 5432
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - rover_db_volume:/var/lib/postgresql/data

  app:
    build: .
    container_name: rover_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://mert:password123@db:5432/roverdb
      - ENV=development # Use 'production' on the Pi
      - JWT_SECRET_KEY=a-super-secret-key-that-is-long-and-secure
      - SECRET_KEY=another-super-secret-key-for-flask-sessions
    privileged: true
    volumes:
      - .:/app
      - /app/.venv  # This "hides" the container's venv from your host folder
    ports:
      - "5000:5000"

volumes:
  rover_db_volume: