version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: rover_db
    restart: always
    environment:
      - POSTGRES_USER=mert
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=roverdb
    ports:
      - "54320:5432"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - rover_db_volume:/var/lib/postgresql/data

  app:
    build: .
    container_name: rover_app
    depends_on:
      - db
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgresql://mert:password123@db:5432/roverdb
      - JWT_SECRET_KEY=a-super-secret-key-that-is-long-and-secure
      - SECRET_KEY=another-super-secret-key-for-flask-sessions
    privileged: true
    ports:
      - "5000:5000"  # Optional: You can remove this if you ONLY want access via Tunnel
    # Note: Volumes for code are removed for production stability

  # --- NEW SERVICE ---
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: rover_tunnel
    restart: always
    command: tunnel --url http://app:5000
    depends_on:
      - app

volumes:
  rover_db_volume: